#!/usr/bin/env python3
"""
Generate Contest Summary - Tạo summary report cho cả contest

Usage:
    python3 generate_summary.py ~/Desktop/hsghanoi-2024-2025/
"""

import argparse
import sys
from pathlib import Path
from datetime import datetime

def analyze_contest(contest_folder: Path) -> dict:
    """Analyze contest folder and generate statistics"""
    
    summary = {
        'contest_name': contest_folder.name,
        'generated_at': datetime.now().isoformat(),
        'total_problems': 0,
        'total_lines': 0,
        'total_files': 0,
        'problems': [],
        'exported_formats': set()
    }
    
    for problem_folder in sorted(contest_folder.iterdir()):
        if not problem_folder.is_dir():
            continue
        
        problem_info = {
            'name': problem_folder.name,
            'lines': 0,
            'has_solution_py': False,
            'has_solution_cpp': False,
            'has_lesson_md': False,
            'exported_formats': []
        }
        
        # Check files
        for file in problem_folder.iterdir():
            if file.name == "lesson.md":
                problem_info['has_lesson_md'] = True
                with open(file, 'r', encoding='utf-8') as f:
                    problem_info['lines'] = len(f.read().split('\n'))
                summary['total_lines'] += problem_info['lines']
            
            elif file.name == "solution.py":
                problem_info['has_solution_py'] = True
            
            elif file.name == "solution.cpp":
                problem_info['has_solution_cpp'] = True
            
            elif file.suffix in ['.pdf', '.docx', '.html']:
                problem_info['exported_formats'].append(file.suffix[1:].upper())
                summary['exported_formats'].add(file.suffix[1:].upper())
            
            summary['total_files'] += 1
        
        if problem_info['has_lesson_md']:
            summary['total_problems'] += 1
            summary['problems'].append(problem_info)
    
    return summary


def generate_markdown_summary(summary: dict) -> str:
    """Generate markdown summary"""
    
    md = f"""# 📊 Contest Summary: {summary['contest_name']}

**Generated:** {summary['generated_at'][:10]}

---

## 📈 Statistics

| Metric | Value |
|--------|-------|
| Total Problems | {summary['total_problems']} |
| Total Lines | {summary['total_lines']:,} |
| Total Files | {summary['total_files']} |
| Exported Formats | {', '.join(sorted(summary['exported_formats'])) or 'None'} |

---

## 📚 Problems

| # | Problem | Lines | Python | C++ | Exported |
|---|---------|-------|--------|-----|----------|
"""
    
    for i, problem in enumerate(summary['problems'], 1):
        exported = ', '.join(sorted(problem['exported_formats'])) if problem['exported_formats'] else '❌'
        md += f"| {i} | {problem['name']} | {problem['lines']:,} | {'✅' if problem['has_solution_py'] else '❌'} | {'✅' if problem['has_solution_cpp'] else '❌'} | {exported} |\n"
    
    md += f"""
---

## 📁 Folder Structure

```
{summary['contest_name']}/
"""
    
    for problem in summary['problems']:
        md += f"├── {problem['name']}/\n"
        if problem['has_lesson_md']:
            md += f"│   ├── lesson.md ({problem['lines']:,} lines)\n"
        if problem['has_solution_py']:
            md += f"│   ├── solution.py\n"
        if problem['has_solution_cpp']:
            md += f"│   ├── solution.cpp\n"
        for fmt in sorted(problem['exported_formats']):
            md += f"│   ├── lesson.{fmt.lower()}\n"
    
    md += """```

---

## ✅ Quality Checklist

"""
    
    # Quality checks
    all_have_solution_py = all(p['has_solution_py'] for p in summary['problems'])
    all_have_solution_cpp = all(p['has_solution_cpp'] for p in summary['problems'])
    all_exported = all(len(p['exported_formats']) >= 3 for p in summary['problems'])
    min_lines = min((p['lines'] for p in summary['problems']), default=0)
    
    md += f"- [{'✅' if all_have_solution_py else '❌'}] All problems have Python solution\n"
    md += f"- [{'✅' if all_have_solution_cpp else '❌'}] All problems have C++ solution\n"
    md += f"- [{'✅' if all_exported else '❌'}] All problems exported to PDF/DOCX/HTML\n"
    md += f"- [{'✅' if min_lines >= 300 else '❌'}] All lessons have 300+ lines (min: {min_lines})\n"
    
    md += f"""
---

**Generated by cp-teacher generate_summary.py**
"""
    
    return md


def main():
    parser = argparse.ArgumentParser(description="Generate contest summary")
    parser.add_argument("contest_folder", help="Path to contest folder")
    parser.add_argument("--output", "-o", help="Output file (default: SUMMARY.md in contest folder)")
    parser.add_argument("--print", action="store_true", help="Print summary to stdout")
    
    args = parser.parse_args()
    
    contest_folder = Path(args.contest_folder)
    
    if not contest_folder.exists():
        print(f"❌ Contest folder not found: {contest_folder}")
        sys.exit(1)
    
    # Analyze
    print(f"🔍 Analyzing contest: {contest_folder.name}...")
    summary = analyze_contest(contest_folder)
    
    # Generate markdown
    md_content = generate_markdown_summary(summary)
    
    # Output
    if args.print:
        print("\n" + md_content)
    
    # Save to file
    output_path = args.output or contest_folder / "SUMMARY.md"
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(md_content)
    
    print(f"✅ Summary saved to: {output_path}")
    
    # Print quick stats
    print(f"\n📊 Quick Stats:")
    print(f"   Problems: {summary['total_problems']}")
    print(f"   Total lines: {summary['total_lines']:,}")
    print(f"   Total files: {summary['total_files']}")
    print(f"   Formats: {', '.join(sorted(summary['exported_formats'])) or 'None'}")


if __name__ == "__main__":
    main()
